--тип у которой больше всего аудиторий
select top(1) AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, (count( AUDITORIUM.AUDITORIUM_TYPE))[Тип аудитории] from AUDITORIUM_TYPE inner join AUDITORIUM
on AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
group by AUDITORIUM_TYPE.AUDITORIUM_TYPENAME

select top (1) AUDITORIUM_TYPE.AUDITORIUM_TYPENAME , count (AUDITORIUM.AUDITORIUM)[кол-во]
from AUDITORIUM inner join AUDITORIUM_TYPE 
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
group by AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
