select GROUPS.FACULTY[Факультет], PULPIT.PULPIT[Кафедра],
PROGRESS.SUBJECT[Предмет], STUDENT.NAME[Имя], PROGRESS.NOTE[Оценка(число)],

case
when(PROGRESS.NOTE = 6) then 'шесть'
when(PROGRESS.NOTE = 7) then 'семь'
when(PROGRESS.NOTE = 8) then 'восемь'
end [Оценка]

from STUDENT, PROGRESS,
GROUPS, PULPIT, SUBJECT

where PROGRESS.NOTE between 6 and 8
and GROUPS.IDGROUP = STUDENT.IDGROUP
and PROGRESS.SUBJECT = SUBJECT.SUBJECT
and PULPIT.PULPIT = SUBJECT.PULPIT
and STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT

order by GROUPS.FACULTY, PULPIT.PULPIT,
PROGRESS.SUBJECT, STUDENT.NAME, Оценка