select 
	STUDENT.NAME,
	SUBJECT.SUBJECT,
	FACULTY.FACULTY, 
	PULPIT.PULPIT,   
	PROFESSION.QUALIFICATION,
	PROGRESS.NOTE

		from FACULTY
	join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY
	join GROUPS on PROFESSION.PROFESSION = GROUPS.PROFESSION
	join STUDENT on GROUPS.IDGROUP = STUDENT.IDGROUP
	join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT
	join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT 
		where PROGRESS.NOTE  between 6 and 8

ORDER BY(case PROGRESS.NOTE 
when 7 then 1
when 8 then 2
when 6 then 3 end ) ;