use UNIVER
--гюдюмхе мнлеп 1
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

--гюдюмхе мнлеп 2
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE 'йНЛОЭЧРЕП%'


--гюдюмхе мнлеп 3 
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM, AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE


select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM, AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE AND  AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE 'йНЛОЭЧРЕП%'

--гюдюмхе мнлеп 4
SELECT	STUDENT.IDSTUDENT,STUDENT.NAME ,GROUPS.IDGROUP ,FACULTY.FACULTY_NAME ,PULPIT.PULPIT_NAME ,SUBJECT.SUBJECT_NAME,
Case PROGRESS.NOTE
when 6 then'нжемйю ьеярэ'
when 7 then'нжемйю яелэ'
when 8 then'нжемйю бняелэ'
end  нЖЕМЙЮ
From STUDENT INNER JOIN PROGRESS
On	STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT and PROGRESS.NOTE between 6 and 8
INNER JOIN Subject
On PROGRESS.SUBJECT=SUBJECT.SUBJECT
INNER JOIN GROUPS
On STUDENT.IDGROUP=GROUPS.IDGROUP
INNER JOIN FACULTY
On GROUPS.FACULTY=FACULTY.FACULTY
INNER JOIN PULPIT
On SUBJECT.PULPIT=PULPIT.PULPIT
ORDER BY STUDENT.NAME,FACULTY.FACULTY,PULPIT.PULPIT


--гюдюмхе мнлеп 5

SELECT	STUDENT.IDSTUDENT,STUDENT.NAME ,GROUPS.IDGROUP ,FACULTY.FACULTY_NAME ,PULPIT.PULPIT_NAME ,SUBJECT.SUBJECT_NAME,
Case PROGRESS.NOTE
when 6 then'нжемйю ьеярэ'
when 7 then'нжемйю яелэ'
when 8 then'нжемйю бняелэ'
end  нЖЕМЙЮ
From STUDENT INNER JOIN PROGRESS
On	STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT and PROGRESS.NOTE between 6 and 8
INNER JOIN Subject
On PROGRESS.SUBJECT=SUBJECT.SUBJECT
INNER JOIN GROUPS
On STUDENT.IDGROUP=GROUPS.IDGROUP
INNER JOIN FACULTY
On GROUPS.FACULTY=FACULTY.FACULTY
INNER JOIN PULPIT
On SUBJECT.PULPIT=PULPIT.PULPIT
ORDER BY
(Case PROGRESS.NOTE
when 6 then 3
when 7 then 1
when 8 then 2
end
)


--гюдюмхе мнлеп 6
Select PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME,'***')
From PULPIT Left Outer JOIN TEACHER
On PULPIT.PULPIT=TEACHER.PULPIT
--гюдюмхе мнлеп 7
Select PULPIT.PULPIT_NAME, isnull(PULPIT.PULPIT_NAME,'***')
From  TEACHER Left Outer JOIN PULPIT
On PULPIT.PULPIT=TEACHER.PULPIT

Select PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME,'***')
From  TEACHER Right Outer JOIN PULPIT
On PULPIT.PULPIT=TEACHER.PULPIT

--гюдюмхе 8
Select PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
From PULPIT FULL Outer JOIN TEACHER 
On PULPIT.PULPIT=TEACHER.PULPIT

--яндйпфхр дюммше кебни ю опюбни мерс)
Select PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
From   PULPIT FULL Outer JOIN TEACHER
On PULPIT.PULPIT=TEACHER.PULPIT
WHERE TEACHER.TEACHER_NAME IS NULL
--яндепфхр дюммше опюбни ю кебюъ опноюкю)
Select PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
From   PULPIT FULL Outer JOIN TEACHER
On PULPIT.PULPIT=TEACHER.PULPIT
WHERE PULPIT.PULPIT_NAME IS NULL

--яндепфхр нае рюакхжш
Select PULPIT.PULPIT_NAME,isnull(TEACHER.TEACHER_NAME,'***')
From   PULPIT FULL Outer JOIN TEACHER
On PULPIT.PULPIT=TEACHER.PULPIT
WHERE PULPIT.PULPIT_NAME  IS NOT  NULL AND TEACHER.TEACHER_NAME IS NOT NULL
--гюдюмхе 9
SELECT	AUDITORIUM.AUDITORIUM ,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
From AUDITORIUM	CROSS JOIN AUDITORIUM_TYPE
Where	AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE;


