use UNIVER
--1
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
--2
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
From AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE ' ÓÏÔ¸˛ÚÂ%'
--3
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
FROM AUDITORIUM , AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
From AUDITORIUM , AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE ' ÓÏÔ¸˛ÚÂ%'

--4

SELECT	STUDENT.IDSTUDENT,STUDENT.NAME ,GROUPS.IDGROUP ,FACULTY.FACULTY_NAME ,PULPIT.PULPIT_NAME ,SUBJECT.SUBJECT_NAME, 
Case PROGRESS.NOTE
when 6 then'Œ÷≈Õ ¿ ÿ≈—“‹'
when 7 then'Œ÷≈Õ ¿ —≈Ã‹'
when 8 then'Œ÷≈Õ ¿ ¬Œ—≈Ã‹'
end  ŒˆÂÌÍ‡
From STUDENT INNER JOIN PROGRESS
On	STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT and PROGRESS.NOTE between 6 and 8
INNER JOIN Subject
On PROGRESS.SUBJECT=SUBJECT.SUBJECT
INNER JOIN GROUPS
On STUDENT.IDGROUP=GROUPS.IDGROUP
INNER JOIN FACULTY
On GROUPS.FACULTY=FACULTY.FACULTY
INNER JOIN PULPIT
On SUBJECT.PULPIT=PULPIT.PULPIT
ORDER BY STUDENT.NAME,FACULTY.FACULTY,PULPIT.PULPIT

	