use UNIVER
--задание номер 1
Select PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME
From PULPIT,FACULTY
where PULPIT.FACULTY=FACULTY.FACULTY
and FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY
FROM PROFESSION
where(PROFESSION.PROFESSION_NAME Like'%технолог%'))

--задание номер 2
Select PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME
From PULPIT Inner JOIN FACULTY
ON PULPIT.FACULTY=FACULTY.FACULTY
Where FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY
FROM PROFESSION
where(PROFESSION.PROFESSION_NAME Like'%технолог%'))

--задание номер 3
Select PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME,PROFESSION.PROFESSION_NAME
From PULPIT Inner JOIN FACULTY
ON PULPIT.FACULTY=FACULTY.FACULTY Inner JOIN PROFESSION
ON FACULTY.FACULTY = PROFESSION.FACULTY
where(PROFESSION.PROFESSION_NAME Like'%технолог%')

--задание номер 4
Select AUDITORIUM,AUDITORIUM_TYPE,AUDITORIUM_CAPACITY
From AUDITORIUM a
where AUDITORIUM =(Select  AUDITORIUM FROM AUDITORIUM aa
WHERE aa.AUDITORIUM_TYPE=a.AUDITORIUM_TYPE ORDER BY AUDITORIUM_CAPACITY desc)

--задание номер 5
select FACULTY_NAME
from FACULTY
WHERE not exists (select  *  from PULPIT
where PULPIT.FACULTY = FACULTY.FACULTY)

--задание номер 6
SELECT top(1)
(select avg(PROGRESS.NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'СУБД') [subd] ,
(select avg(PROGRESS.NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'БД') [bd] ,
(select avg(PROGRESS.NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'ОАиП') [oop] 
From PROGRESS

--задание номер 7
select SUBJECT,NOTE 
FROM PROGRESS
Where NOTE < all(select  NOTE from PROGRESS
where SUBJECT like 'С%')

--задание номер 8
select SUBJECT,NOTE 
FROM PROGRESS
Where NOTE < any (select  NOTE from PROGRESS
where SUBJECT like 'С%')

--задание со звездой

Select IDGROUP,NAME,BDAY
From STUDENT 
where exists(Select BDAY FROM STUDENT
WHERE NAME != NAME and BDAY=BDAY)